server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
      
# Logging
logging:

  level: INFO

  loggers:
    # Set info logging for Flax code
    "uk.co.flax": DEBUG
    
  appenders:

    # Set up console logging  
    - type: console
      threshold: ALL
      target: stderr
      
    # Set up file logging
  
    # Settings for logging to a file.
    - type: file
  
      # Do not write log statements below this threshold to the file.
      threshold: ALL
  
      # The time zone in which dates should be displayed.
      timeZone: UTC
  
      # A custom Logback format string.
      logFormat: null
  
      # The file to which statements will be logged.
      #
      # If enabled is true, this must be specified.
      currentLogFilename: logs/ontology-webapp.log
  
      # When the log file rolls over, the file will be archived to
      # app-2012-03-15.log.gz, example.log will be truncated,
      # and new statements written to it.
      #
      # If archive is true, this must be specified.
      archivedLogFilenamePattern: logs/ontology-webapp-%d.log.gz
  
      # The maximum number of log files to archive.
      archivedFileCount: 5

# Solr configuration    
solr:
  
  # The URL for the Ontology Solr core
  ontologyUrl: "http://localhost:8983/solr/ontology"
  
  # The default ontology search request handler
  ontologyRequestHandler: "/ontologySearch"
  
  # The URL for the Document Solr core
  documentUrl: "http://localhost:8983/solr/documents"
  
  # The request handler for searching documents (by string)
  documentRequestHandler: "/documentSearch"
  
  # The request handler for searching documents (by URI)
  documentUriRequestHandler: "/uriSearch"
  
